name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers when you push a tag like "v1.0.0"

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Electron App
        run: npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist-electron/BinksBrowser Setup *.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
